export default {
	GET_USER_DATA:'GET_USER_DATA',
	GET_DRIVERS:'GET_DRIVERS',
	GET_JOBS:'GET_JOBS',
	ACCEPTED_BIDS:'ACCEPTED_BIDS',
	GET_INACTIVE_DRIVERS:'GET_INACTIVE_DRIVERS',
	DRIVERS_LOCATION:'DRIVERS_LOCATION'
};